# Generated by Django 5.0.2 on 2024-02-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=30, unique=True)),
                ('taskDescription', models.TextField(max_length=300)),
            ],
        ),
    ]
